"""
Kodex Agent State Definition.

Defines the typed state schema used by the LangGraph state machine.
Every node reads from and writes to this shared state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Annotated, Any, TypedDict

from langgraph.graph.message import add_messages


# =============================================================================
# Error Representation
# =============================================================================
class CodeError(TypedDict):
    """A single detected code error."""

    file_path: str
    line: int
    column: int
    code: str           # e.g. "E501", "F841"
    message: str
    severity: str       # "error" | "warning"
    source: str         # "ruff" | "pytest" | "mypy"


# =============================================================================
# Fix Proposal
# =============================================================================
class ProposedFix(TypedDict):
    """A proposed code fix generated by the LLM."""

    file_path: str
    original_content: str
    patched_content: str
    explanation: str
    confidence: int           # 0-100
    diff: str                 # Unified diff string
    affected_files: list[str] # Files potentially impacted


# =============================================================================
# Test Result
# =============================================================================
class TestResult(TypedDict):
    """Result from running tests in the sandbox."""

    passed: bool
    total: int
    failures: int
    errors: int
    duration: float
    output: str
    failed_tests: list[str]


# =============================================================================
# Session Event (for audit trail)
# =============================================================================
class SessionEvent(TypedDict):
    """A single event in the session audit trail."""

    timestamp: str
    event_type: str
    data: dict[str, Any]
    duration_ms: float


# =============================================================================
# Agent State — The core state schema for LangGraph
# =============================================================================
class AgentState(TypedDict):
    """
    Shared state for the Kodex LangGraph agent.

    This TypedDict is the "memory" of the agent. Every node function
    receives the full state and returns a partial dict of updates.
    LangGraph merges updates into the state automatically.
    """

    # ─── Core Flow ──────────────────────────────────────────────────────
    repo_path: str
    errors: list[CodeError]
    current_error_index: int
    current_error: CodeError | None
    retrieved_context: list[dict[str, Any]]
    proposed_fix: ProposedFix | None
    fix_approved: bool | None
    test_results: TestResult | None
    regression_results: TestResult | None
    fix_history: list[dict[str, Any]]

    # ─── LLM Conversation ──────────────────────────────────────────────
    messages: Annotated[list, add_messages]

    # ─── Tracking ──────────────────────────────────────────────────────
    token_usage: dict[str, Any]
    session_id: str
    session_events: list[SessionEvent]

    # ─── Control ───────────────────────────────────────────────────────
    max_retries: int
    current_retry: int
    mode: str               # "auto" | "review"
    status: str             # "running" | "paused" | "complete" | "error"


# =============================================================================
# State Factory
# =============================================================================
def create_initial_state(
    repo_path: str,
    session_id: str,
    mode: str = "review",
    max_retries: int = 3,
) -> AgentState:
    """
    Create a fresh agent state with sensible defaults.

    Args:
        repo_path: Path to the repository to heal.
        session_id: Unique identifier for this session.
        mode: Operating mode ('auto' or 'review').
        max_retries: Maximum fix attempts per error.

    Returns:
        AgentState: Initialized state dictionary.
    """
    return AgentState(
        repo_path=repo_path,
        errors=[],
        current_error_index=0,
        current_error=None,
        retrieved_context=[],
        proposed_fix=None,
        fix_approved=None,
        test_results=None,
        regression_results=None,
        fix_history=[],
        messages=[],
        token_usage={
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "embedding_tokens": 0,
            "total_cost": 0.0,
            "llm_calls": 0,
        },
        session_id=session_id,
        session_events=[],
        max_retries=max_retries,
        current_retry=0,
        mode=mode,
        status="running",
    )
